export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_LOCATIONS_START='FETCH_LOCATIONS_START';
export const FETCH_LOCATIONS_FAIL='FETCH_LOCATIONS_FAIL';
export const FETCH_LOCATIONS_SUCCESS='FETCH_LOCATIONS_SUCCESS';

export const FETCH_COUNTRY_START = 'FETCH_COUNTRY_START';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAIL = 'FETCH_COUNTRY_FAIL';

export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_GRID = 'UPDATE_GRID';
export const LOAD_TASKS = 'LOAD_TASKS';
export const SAVE_TASKS = 'SAVE_TASKS';
export const SAVE_TASKS_SUCCESS = 'SAVE_TASKS_SUCCESS';
export const SAVE_TASKS_FAIL = 'SAVE_TASKS_FAIL';
export const DELETE_ALL_TASKS = 'DELETE_ALL_TASKS';

export const FETCH_SONG_START = 'FETCH_SONG_START';
export const FETCH_SONG_FAIL = 'FETCH_SONG_FAIL';
export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';